# override global pinning to stay on CUDA 12.0
# because CatBoost does not support CUDA versions 12.3+ yet: https://github.com/catboost/catboost/issues/2755
c_stdlib_version:                                                                 # [linux]
  - 2.17                                                                          # [linux]
  - 2.17                                                                          # [linux]
c_compiler_version:                                                               # [linux]
  - 14                                                                            # [linux]
  - 12                                                                            # [linux]
cxx_compiler_version:                                                             # [linux]
  - 14                                                                            # [linux]
  - 12                                                                            # [linux]
fortran_compiler_version:                                                         # [linux]
  - 14                                                                            # [linux]
  - 12                                                                            # [linux]
cuda_compiler_version:                                                            # [linux]
  - None                                                                          # [linux]
  - 12.0                                                                          # [linux]
cuda_compiler_targets:                                                            # [linux]
  - ""                                                                            # [linux]
  - "50-virtual;60-virtual;61-real;70-virtual;75-real;80-real;86-real;89-real;90" # [linux]
cudnn:
  - None                                                                          # [linux]
  - '9'                                                                           # [linux]
